apiVersion: v1
kind: Namespace
metadata:
  name: chatbot
  labels:
    name: chatbot
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: chatbot
data:
  BACKEND_ENV: "production"
  DEBUG: "False"
  LOG_LEVEL: "INFO"
  VITE_API_URL: "http://backend-service:8000"
  VITE_WS_URL: "ws://backend-service:8000/ws"
